language: java
env: MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m" GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=192m" TERM="dumb"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script:
  - rm -rf core/build
  - rm -rf rundeckapp/build
# whitelist
branches:
  only:
    - development

notifications:
  irc:
    - "irc.freenode.org#rundeck"
  #email: false


